name: "concorrencia"
run-name: "Pipeline (${{inputs.chave-concorrencia}}) executado pela ${{github.run_number}} vez"

on:
  workflow_dispatch:
    inputs: 
      chave-concorrencia:
        type: string
        default: "pipe-test"

concurrency: "${{inputs.chave-concorrencia}}"

jobs:
  job-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Execucao step (job-test)"
        run: |
          sleep 120;
          echo "Action executada"
