name: "concorrencia"
run-name: "Pipeline (${{inputs.chave-concorrencia}}) executado pela ${{github.run_number}} vez"

on:
  workflow_dispatch:
    inputs: 
      chave-concorrencia:
        type: string
        default: "pipe-test"

jobs:
  job-test:
    concurrency: "${{inputs.chave-concorrencia}}"
    runs-on: ubuntu-latest
    steps:
      - name: "Execucao step (job-test)"
        run: |
          sleep 120;
          echo "Action executada"
  job-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: "Execucao step (job-test-2)"
        run: echo "Action executada"
