name: "Exemplo Output"
run-name: "Pipeline (Exemplo Output) executado por ${{github.actor}}"

on:
  workflow_dispatch:

jobs:
  gerando_outputs:
    outputs:
      output_bash: ${{ steps.id_output.outputs.action_random }}
    runs-on: ubuntu-latest
    steps:
      - name: "Gerando output com bash"
        id: id_output
        run: echo "action_random=$(( $RANDOM ))" >> $GITHUB_OUTPUT
      - name: "Acessando resultado do step acima"
        run: echo "Resultado=${{ steps.id_output.outputs.action_random }}"

  buscando_outputs:
    runs-on: ubuntu-latest
    needs: ["gerando_outputs"]
    steps:
      - name: "Buscando outputs do job (gerando_outputs)"
        run: echo "${{ needs.gerando_outputs.outputs.output_bash }}"
