name: "Trigger PR"
run-name: "Pipeline (Trigger PR) executado por ${{github.actor}}"

on:
  pull_request:
    branches: ['main']
    types: closed

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "Executando step da PR"
        run: echo "PR"
      - name: "Adicionar comentario no PR"
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Validacao do PR realizada com sucesso."
            })
