name: "Trigger PR"
run-name: "Pipeline (Trigger PR) executado por ${{github.actor}}"

on:
  pull_request:
    branches: ['dev']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Executando step da PR"
        run: echo "PR"
