name: "Trigger Push"
run-name: "Pipeline (Trigger Push) executado por ${{github.actor}}"

on:
  push:
    branches: ["main", "feature/*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Executando step"
        run: echo "test"
