name: "Validacoes"
run-name: "Pipeline (Validacoes) executado por ${{github.actor}}"

on:
  push:

jobs:
  somente-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Executando apenas branch main"
        run: echo "Branch main executada"
  todos:
    runs-on: ubuntu-latest
    steps:
      - name: "Executando em qualquer branch"
        run: echo "Branch executada"
      - name: "Executando em qualquer branch feature"
        if: ${{ contains(github.ref, 'refs/heads/feature') }}
        run: echo "Branch feature executada"
